version: "3"
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm:latest
    environment:
      DISK_SIZE: "30G"
      ALLOCATE: "N"
      GPU: "Y"
    devices:
      - /dev/kvm
      - /dev/vhost-net
      - /dev/dri
    cap_add:
        - NET_ADMIN
    ports:
      - "5000:5000"
    volumes:
      - ./storage:/storage
    restart: on-failure
    stop_grace_period: 1m