version: '3'
services:
  clash:
    container_name: clash
    image: dreamacro/clash:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    networks:
      - default
      - local
    expose:
      - 7890
    ports:
      - "19090:9090"
    volumes:
      - ./config/clash/config.yaml:/root/.config/clash/config.yaml
    restart: always
  yacd:
    container_name: yacd
    image: haishanh/yacd:latest
    networks:
      - default
    ports:
      - "1234:80"
    restart: always

networks:
  local:
    external: true
    name: local