version: "3"
services:
  chinesesubfinder:
    container_name: chinesesubfinder
    image: allanpk716/chinesesubfinder:latest
    external_links:
      - clash
    volumes:
      - ./config:/config
      - /data/media:/media
      - ./browser:/root/.cache/rod/browser
    environment:
      - PUID=0
      - PGID=0
      - PERMS=true
      - TZ=Asia/Shanghai
      - UMASK=022
      - HTTP_PROXY=http://clash:7890
      - HTTPS_PROXY=http://clash:7890
    restart: always
    networks:
      - default
      - local
    ports:
      - "19035:19035"
      - "19037:19037"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

networks:
  local:
    external:
      name: local