version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

