version: '3'
services:
  hlink:
    container_name: hlink
    image: likun7981/hlink:${HLINK_VERSION}
    volumes:
      - ${DATA_DIR}:/data
      - ./config/hlink/:/hlink_config
    ports:
      - "19090:9090"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HLINK_HOME=/hlink_config
    restart: always
  transmission:
      container_name: transmission
      image: linuxserver/transmission:${TRANSMISSION_VERSION}
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - ./config/transmission/web:/usr/share/transmission/web
        - ./config/transmission/config:/config
        - ./temp:/temp
        - ${DOWNLOADS_DIR}:/downloads
      network_mode: host
      restart: always
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - http_proxy=http://127.0.0.1:7890
      - https_proxy=http://127.0.0.1:7890
    volumes:
      - ./config/jellyfin/config:/config
      - ./config/jellyfin/cache:/cache
      - ./config/jellyfin/font:/usr/share/fonts/truetype/DejaVu
      - ${MEDIA_DIR}:/data
    # 配置N卡转码
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    network_mode: host
    restart: always
#  qbittorrent:
#    container_name: qbittorrent
#    image: linuxserver/qbittorrent:${QBITTORRENT_VERSION}
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#      - WEBUI_PORT=8090
#    volumes:
#      - ./config/qbittorrent/:/config
#      - ./temp:/temp
#      - ${DOWNLOADS_DIR}:/downloads
#    network_mode: host
#    restart: always
#  tmm:
#    container_name: tmm
#    image: tinymediamanager/tinymediamanager:${TMM_VERSION}
#    volumes:
#      - ./config/tmm/data:/data
#      - ./config/tmm/addons:/app/addons
#      - ${MEDIA_DIR}:/media
#    environment:
#      - USER_ID=${PUID}
#      - GROUP_ID=${PGID}
#      - PASSWORD=123456
#    extra_hosts:
#      - api.themoviedb.org:${THEMOVIEDB_IP}
#      - api.tmdb.org:${TMDB_IP}
#    network_mode: host
#    restart: always
#  nas-tools:
#    container_name: nas-tools
#    image: sungamma/nas-tools:${NAS_TOOLS_VERSION}
#    volumes:
#      - ./config/nas-tools:/config
#      - ${DATA_DIR}:/data
#    environment:
#      - UMASK=2
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    network_mode: host
#    restart: always

#  plex:
#    container_name: plex
#    image: plexinc/pms-docker:${PLEX_VERSION}
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#      - device=/dev/dri:/dev/dri
#    volumes:
#      - ./config/plex/database:/config
#      - ./config/plex/transcode/temp:/transcode
#      - ${MEDIA_DIR}:/data
#    network_mode: host
