version: "3"
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - ./config/config:/config
      - ./config/cache:/cache
      - /opt/fonts:/usr/share/fonts/truetype/DejaVu
      - /data/media:/data
    # 配置N卡转码
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    restart: always