version: '3'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    environment:
      - TZ=Asia/Shanghai
      - PLEX_CLAIM=xxxx
    ports:
      - "32400:32400/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./config/database:/config
      - ./config/transcode/temp:/transcode
      - /data/media:/data
    restart: always