#需要先创建local网络：docker network create local
version: "3.8"
services:
  jellyfin:
    container_name: jellyfin
    image: nyanmisaka/jellyfin:latest
    external_links:
      - clash
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - NVIDIA_VISIBLE_DEVICES=all
      - HTTP_PROXY=http://clash:7890
      - HTTPS_PROXY=http://clash:7890
    volumes:
      - ./config/config:/config
      - ./config/cache:/cache
      - /data/media:/data
    privileged: true
    # 配置N卡转码
    runtime: nvidia
    networks:
      - default
      - local
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    restart: always

networks:
  local:
    external: true
    name: local