#需要先创建local网络：docker network create local
version: "3"
services:
  emby:
    container_name: emby
    image: lovechen/embyserver:latest
    external_links:
      - clash
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - GIDLIST=0
      - HTTP_PROXY=http://clash:7890
      - HTTPS_PROXY=http://clash:7890
    volumes:
      - ./config/config:/config
      - ./config/cache:/cache
      - /data/media:/data
    devices:
      - /dev/dri:/dev/dri
    networks:
      - default
      - local
    restart: always

networks:
  local:
    external:
      name: local